[target.x86_64-pc-windows-msvc]
rustflags = ["-Ctarget-feature=+crt-static", "-Clink-arg=/safeseh:no"]

[target.i686-pc-windows-msvc]
rustflags = ["-Ctarget-feature=+crt-static", "-Clink-arg=/safeseh:no"]

[target.i586-pc-windows-msvc]
rustflags = ["-Ctarget-feature=+crt-static", "-Clink-arg=/safeseh:no"]
